### ISSUE TITLE
Which copy strategy does Modf implement

### ISSUE THREAD

**Issue by mdbergmann** [smithzvk/modf#6]
Hi.

This is more a question. Didn't know where to ask else.

In FP there are basically two concepts: shallow copy, used for copy-on-write, and deep copy, used for passing data in/out of immutable program areas.

From what I have tried on standard-object classes it seems to do a shallow copy which creates a new instance of the a class but keeps any slots intact except the one that is modified.
Is that kind of correct?

**Comment by smithzvk** [comment]
It is shallow, or as shallow as possible to perform the "modf" you requested (which may require copying several levels of data structure to recreate the desired return value).

Interestingly, you comment revealed a bug in PR #5 .

**Comment by mdbergmann** [comment]
Thanks
